# Generated by Django 5.0.1 on 2024-01-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_creation_date_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='technology', max_length=255),
        ),
    ]
