# Generated by Django 5.0.1 on 2024-01-14 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.TextField(default='product', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/product_images/default.jpg', upload_to='../static/product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
