# Generated by Django 5.0.1 on 2024-01-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_alt_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='../static/product_images/default.jpg', upload_to='../static/product_images/')),
            ],
        ),
    ]
