# Generated by Django 5.0.1 on 2024-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_flyer_delete_flyers_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='category',
            field=models.CharField(default='main', max_length=255),
        ),
    ]
